# permissions for end users to view houses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: house-viewer-role
rules:
- apiGroups:
  - house.teddyking.github.io
  resources:
  - houses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - house.teddyking.github.io
  resources:
  - houses/status
  verbs:
  - get
