# permissions for end users to edit houses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: house-editor-role
rules:
- apiGroups:
  - house.teddyking.github.io
  resources:
  - houses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - house.teddyking.github.io
  resources:
  - houses/status
  verbs:
  - get
