# permissions for end users to edit searches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: search-editor-role
rules:
- apiGroups:
  - house.teddyking.github.io
  resources:
  - searches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - house.teddyking.github.io
  resources:
  - searches/status
  verbs:
  - get
