# permissions for end users to view searches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: search-viewer-role
rules:
- apiGroups:
  - house.teddyking.github.io
  resources:
  - searches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - house.teddyking.github.io
  resources:
  - searches/status
  verbs:
  - get
